### PR TITLE
Update units.csv #105

### PR DESCRIPTION
**Pull request by atomczak**
- replace semicolons with commas
- change UTF-16LE to UTF-8

### CODE REVIEW

**Review by Baars-IT — CHANGES_REQUESTED** [review]
Hi Artur,
It looks like you saved the CSV file as some kind of binary. Make sure it is just a text file!

**Comment by atomczak** [comment]
Weird, it is just a CSV file, have a look at the contents: https://github.com/buildingSMART/bSDD/blob/759b6e77cd942d659a53aba5751c13e2aa184be4/DataFiles/units.csv?plain=1 
Also loads fine in Excel, however I see odd encoding: `Î”Â°C`

**Comment by Erik-RN** [comment]
Can you open it in Notepad and then save it? Then it's surely a text file

**Comment by Baars-IT** [comment]
Strange why github cannot display it.
I will push PR and run the import.

**Pull request merged**
